apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: kamalbhaiii/k3s-frontend:armv7
        ports:
        - containerPort: 5173

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30090
